---
# tasks file for sgreen.wordpress

- name: Copy wordpress.zip into tmp
  copy: src=wordpress.zip dest=/tmp/wordpress.zip
- name: Unzip WordPress
  unarchive: src=/tmp/wordpress.zip dest=/tmp copy=no creates=/tmp/wordpress/wp-settings.php
- name: Create project folder
  file: dest=/var/www/html/wordpress state=directory
- name: Copy WordPress files
  command: cp -a /tmp/wordpress/. /var/www/html/wordpress creates=/var/www/html/wordpress/wp-settings.php
- name: Create WordPress MySQL database
  mysql_db: name={{database_name}} state=present
- name: Create WordPress MySQL user
  mysql_user: name={{database_user}} host=localhost password={{database_password}} priv=wordpress.*:ALL
- name: Create wp-config
  template: src=wp-config.php dest=/var/www/html/wordpress/wp-config.php
